# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a64ee25e7dfa9b466cdd3569238243e189713ae342980f395db3168277d29119df777a9a8bba9721be0f9b33829a77aae83afc68b8f914099db90cb74ab480d9

test:
  secret_key_base: c1412f9c9a976df14daa0092cec43829afa336bd7ca1a49d87e539ed9502646ec38c0398269e2695714ed54c96f3d77de59e2721a0f26b4a618830c637ee40ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
